version: '3'

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=uni"
      - "POSTGRES_PASSWORD=2siSD4uO5UZ9DNfijxFN7h1TG0jd2hEN"
      - "POSTGRES_DB=uni"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=3nt3.de@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=2siSD4uO5UZ9DNfijxFN7h1TG0jd2hEN"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  db_data:
  pgadmin_data:
